net.sf.jasperreports.default.resource.bundle.encoding=UTF-8
net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.notofamily=fonts/fontsfamily.xml